env:
  browser: true
  es2021: true
  jest: true
extends: 
  - airbnb-base
  - 'plugin:jest/recommended'
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  linebreak-style: "off"
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  # no-param-reassign: 0